chore: add verification to pre-commit hook

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,8 +1,7 @@
-# branch="$(git rev-parse --abbrev-ref HEAD)"
-
-# if [ "$branch" = "main" ]; then
-#   echo "You can't commit directly to main branch"
-#   exit 1
-# fi
+branch="$(git rev-parse --abbrev-ref HEAD)"
+if [ "$branch" = "main" ]; then
+  echo "You can't commit directly to main branch"
+  exit 1
+fi
 
 npm run lint
